# This is a fake Dockerfile, that is generated automatically
# to list the images contained in a real docker-compose file.
# This hack enables dependabot alerts for docker-compose files,
# which right now are not supported
#
# Last update: dom 3 set 2023, 13:13:44, CEST
# images extracted from ../control-plane/docker-compose.yml

FROM traefik:v2.10
RUN echo traefik:v2.10
 
FROM nginx
RUN echo nginx
 
FROM grafana/grafana:latest
RUN echo grafana/grafana:latest
 
FROM prom/prometheus
RUN echo prom/prometheus
 
FROM prom/node-exporter
RUN echo prom/node-exporter
 
FROM gcr.io/cadvisor/cadvisor:v0.47.2
RUN echo gcr.io/cadvisor/cadvisor:v0.47.2
 
FROM grafana/loki:2.8.0
RUN echo grafana/loki:2.8.0
 
FROM grafana/promtail:2.8.0
RUN echo grafana/promtail:2.8.0
 
