{
 "title": "morse chat Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "bad events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(morsechat_bad_messages[10m])",
     "legendFormat": "n word"
    },
    {
     "expr": "increase(morsechat_connection_denied{reason=\"bad\"}[10m])",
     "legendFormat": "bad user"
    },
    {
     "expr": "increase(morsechat_connection_denied{reason=\"max_ip\"}[10m])",
     "legendFormat": "clients with same ip"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(container_memory_usage_bytes{name=\"morsechat-go-morse-1\"}[30m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "wpm distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(morsechat_messages_wpm_bucket[1h])))",
     "legendFormat": "wpm distribution"
    }
   ]
  },
  {
   "title": "Online users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "morsechat_connected_users{channel!=\"\"}",
     "legendFormat": "{{channel}}"
    },
    {
     "expr": "morsechat_connected_users{channel=\"\"}",
     "legendFormat": "users in limbo"
    }
   ]
  },
  {
   "title": "messages sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(morsechat_messages[30m])",
     "legendFormat": "messages"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } }
 ]
}