- name: configure the personal vps
  hosts: hetzner_vps
  tasks:
    - name: test sudo access
      become: true
      command: id -u
      register: id_output
    - assert:
        that: id_output.stdout == '0'

  # mariadb http://youdidwhatwithtsql.com/simple-mariadb-deployment-ansible/2311/



